<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Class1.cs" />
    <Compile Remove="Models\User.cs" />
    <Compile Remove="Common\**" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Remove="Common\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Common\**" />
  </ItemGroup>

</Project>
